# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gmaps4rails}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Your Name"]
  s.date = %q{2010-10-08}
  s.email = %q{you@email.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/gmaps4rails/gmaps_controller.rb",
     "app/helpers/application_helper.rb",
     "app/helpers/gmaps4rails/Gmaps_helper.rb",
     "app/models/gmaps4rails/gmaps.rb",
     "app/views/gmaps4rails/_map.html.erb",
     "app/views/gmaps4rails/gmaps/index.xml.builder",
     "config/routes.rb",
     "lib/acts_as_gmappable/base.rb",
     "lib/application_helper.rb",
     "lib/engine.rb",
     "lib/gmaps4rails.rb",
     "lib/rails/generators/gmaps4rails/gmaps4rails_generator.rb",
     "lib/rails/generators/gmaps4rails/templates/initializer.rb",
     "lib/rails/generators/gmaps4rails/templates/migration.rb",
     "lib/rails/generators/gmaps4rails/templates/schema.rb",
     "lib/rails/railties/tasks.rake"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Description of your gem}
  s.test_files = [
    "test/test_helper.rb",
     "test/unit/gmaps4rails_widget_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

